### ISSUE TITLE
[Bug]: Routing doesn't work when generating Bundles with yaml config

### ISSUE THREAD

**Issue by fashxp** [pimcore/bundle-generator#11]
### Expected behavior

routing works

### Actual behavior

routing doesn't work

### Steps to reproduce

- create bundle
- choose yaml configuration format
- try to open test controller route

**Comment by dvesh3** [comment]
@fashxp Is it for v1?

**Comment by fashxp** [comment]
You mean 1.1?
Not mandatory, also can be part of a bugfix release

**Comment by jkovacevic992** [comment]
From what I understand, it generates something like this:
```
test_homepage:
    path:     /test
    defaults: { _controller: TestBundle\Controller\DefaultController:indexAction }
```
As you can see, one colon is missing, it should be:
```
test_homepage:
    path:     /test
    defaults: { _controller: TestBundle\Controller\DefaultController::indexAction }
```

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/bundle-generator/pull/13
