### ISSUE TITLE
[Bug]: Use preBuildMenu instead of pimcoreReady

### ISSUE THREAD

**Issue by martineiber** [pimcore/bundle-generator#14]
### Expected behavior

preBuildMenu  should be used in the startup.js

### Actual behavior

It still uses the old pimcoreReady function. 

### Steps to reproduce

Generate a new bundle and check the startup.js

**Comment by kingjia90** [comment]
Resolved by #15

**Comment by dvesh3** [comment]
we should add not remove `pimcoreReady` example. please see https://github.com/pimcore/bundle-generator/pull/15#issuecomment-1620428494

**Comment by aryaantony92** [comment]
> we should add not remove `pimcoreReady` example. please see [#15 (comment)](https://github.com/pimcore/bundle-generator/pull/15#issuecomment-1620428494)

Done in https://github.com/pimcore/bundle-generator/pull/16
