### ISSUE TITLE
Error with search_paths?

### ISSUE THREAD

**Issue by hallleron** [pimcore/bundle-generator#4]
Hey,

I tried to create a bundle with this generator, however I always get an error message at the end saying the following:

```
The command was not able to configure everything automatically.
  You'll need to make the following changes manually.


- Edit the composer.json file and register the bundle
  namespace in the "autoload:psr-4" section :
  "Yourcompany\\ModuleTestBundle\\": "bundles/Yourcompany/ModuleTestBundle"
- Edit the application configuration and make sure
  you have added the bundles/Yourcompany/ModuleTestBundle to the Pimcore bundle search paths:
   pimcore:
      bundles:
         search_paths:
             - bundles/Yourcompany/ModuleTestBundle
```

The mentioned composer.json is the one in the project root I guess? So I added it there manually. However the second point is where I am stuck. Where exactly is my "application configuration"? Where do I have to add those lines?

I guess that is why my bundle doesn't show up when I use the console and type pimcore:bundle:list?

**Comment by fashxp** [comment]
application configuration is somewhere in a symfony configuration file that gets loaded, so for example `config/config.yaml`

**Comment by hallleron** [comment]
> application configuration is somewhere in a symfony configuration file that gets loaded, so for example `config/config.yaml`

Thank you very much! I added it to my config/config.yaml now, however when I list the bundles with the console command, the bundle still doesn't show up. Is there anything else I have to do?

**Comment by fashxp** [comment]
eventually `composer dump-autoload`?

**Comment by hallleron** [comment]
> eventually `composer dump-autoload`?

Yes that did the trick! Thanks! =)

**Comment by fashxp** [comment]
👍 improved the output message a bit
